global:
  scrape_interval: 5s

scrape_configs:
  - job_name: server-prometheus-via-dns
    dns_sd_configs: # dns service discovery
      - names:
          - prom-target.rapli.dev
        type: A
        port: 9090
  - job_name: server-node-exporter # Job
    static_configs:
      - targets:
        - localhost:9100
