global:
  scrape_interval: 5s

scrape_configs:
  - job_name: server-prometheus # Job
    static_configs:
      - targets:
        - localhost:9090
  - job_name: server-node-exporter # Job
    static_configs:
      - targets:
        - localhost:9100
